if (import.meta.env.DEV) {
  import('react-grab');
}

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { configureBoneyard } from 'boneyard-js/react';
import './index.css';
import App from './App.tsx';
import { ThemeProvider } from './themes/ThemeProvider';

configureBoneyard({
  color: 'hsl(var(--bg-3))',
  darkColor: 'hsl(var(--bg-3))',
  animate: 'shimmer',
  shimmerColor: 'hsl(var(--bg-2))',
  darkShimmerColor: 'hsl(var(--bg-2))',
  speed: '1.6s',
  stagger: 60,
  transition: 220,
});

// Pre-built bones registry — generated by `npm run boneyard:build`.
// Stub file exists for build resolution; Skeleton uses fallback prop until built.
import './bones/registry';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ThemeProvider>
      <App />
    </ThemeProvider>
  </StrictMode>,
);
